spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?serverTimezone=Asia/Taipei
    username: root
    password: isabella1637
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
allowed:
  origins: http://localhost:4200
#  mvc:
#    servlet:
#      path: /api
okta:
  oauth2:
    client-id: 0oa786pf7nppWtDiH5d7
    issuer: https://dev-07369845.okta.com/oauth2/default
