spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?serverTimezone=Asia/Taipei
    username: root
    password: isabella1637
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
allowed:
  origins: http://localhost:4200
#  mvc:
#    servlet:
#      path: /api
